// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8Vfiz2K96oLmh6nUo073dr19HtJqpRt4',
    appId: '1:163722133960:web:d8b35262bdea3af9dd80fd',
    messagingSenderId: '163722133960',
    projectId: 'meditag-2c5ce',
    authDomain: 'meditag-2c5ce.firebaseapp.com',
    storageBucket: 'meditag-2c5ce.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKhra670hr78QBYN31SP-N_Irs91-wFfU',
    appId: '1:163722133960:android:519609755c589050dd80fd',
    messagingSenderId: '163722133960',
    projectId: 'meditag-2c5ce',
    storageBucket: 'meditag-2c5ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXsXgTUdhdTS35YJzro5tslsTDK2ELD-s',
    appId: '1:163722133960:ios:7b14b9ee0aa784dddd80fd',
    messagingSenderId: '163722133960',
    projectId: 'meditag-2c5ce',
    storageBucket: 'meditag-2c5ce.firebasestorage.app',
    iosBundleId: 'com.codelink.medife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXsXgTUdhdTS35YJzro5tslsTDK2ELD-s',
    appId: '1:163722133960:ios:7b14b9ee0aa784dddd80fd',
    messagingSenderId: '163722133960',
    projectId: 'meditag-2c5ce',
    storageBucket: 'meditag-2c5ce.firebasestorage.app',
    iosBundleId: 'com.codelink.medife',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8Vfiz2K96oLmh6nUo073dr19HtJqpRt4',
    appId: '1:163722133960:web:84a2613245385fa7dd80fd',
    messagingSenderId: '163722133960',
    projectId: 'meditag-2c5ce',
    authDomain: 'meditag-2c5ce.firebaseapp.com',
    storageBucket: 'meditag-2c5ce.firebasestorage.app',
  );
}
