// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaRZWkZg5lzMbuSn2j2zuxH2rkiT-kj_I',
    appId: '1:558677571325:web:30abf1ed7f39a45ef13094',
    messagingSenderId: '558677571325',
    projectId: 'meditag-fea95',
    authDomain: 'meditag-fea95.firebaseapp.com',
    storageBucket: 'meditag-fea95.firebasestorage.app',
    measurementId: 'G-MBKXNHDJDQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApPkbS06ujVr6JzDcS8hC-x0GjCui3WuM',
    appId: '1:558677571325:android:b3f40a7c3acb1018f13094',
    messagingSenderId: '558677571325',
    projectId: 'meditag-fea95',
    storageBucket: 'meditag-fea95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOWdx0-2gr6xPOBk0evMlHqX3vUWzVAXw',
    appId: '1:558677571325:ios:fb661d7ca6d039c6f13094',
    messagingSenderId: '558677571325',
    projectId: 'meditag-fea95',
    storageBucket: 'meditag-fea95.firebasestorage.app',
    iosBundleId: 'com.codelink.medife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOWdx0-2gr6xPOBk0evMlHqX3vUWzVAXw',
    appId: '1:558677571325:ios:fb661d7ca6d039c6f13094',
    messagingSenderId: '558677571325',
    projectId: 'meditag-fea95',
    storageBucket: 'meditag-fea95.firebasestorage.app',
    iosBundleId: 'com.codelink.medife',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaRZWkZg5lzMbuSn2j2zuxH2rkiT-kj_I',
    appId: '1:558677571325:web:a62a8eb0494639c1f13094',
    messagingSenderId: '558677571325',
    projectId: 'meditag-fea95',
    authDomain: 'meditag-fea95.firebaseapp.com',
    storageBucket: 'meditag-fea95.firebasestorage.app',
    measurementId: 'G-9Z2977FK91',
  );
}
